
services:
  asterisk:
    image: rhierlmeier/asterisk:latest
    container_name: asterisk
    # Run asterisk in host network mode
    # When not running in host network mode, then additional configuration
    # is required. Please check the corresponding Asterisk documentation.
    # at https://docs.asterisk.org/Configuration/Channel-Drivers/SIP/ 
    network_mode: "host"
    volumes:
      - ./out:/var/spool/asterisk/outgoing
      - ./extensions.conf:/etc/asterisk/extensions.conf
      - ./sip.conf:/etc/asterisk/sip.conf

  mqtt-dial:
    image: rhierlmeier/mqtt-asterisk-dial:latest
    container_name: mqtt-dial
    volumes:
      - ./mqtt-dial-config.yaml:/app/config.yaml
      - ./out:/app/out
